### PR TITLE
Uses new styles.

### PR DESCRIPTION
**Pull request by alfonsserra**

### CODE REVIEW

**Review by oGalceran1 — APPROVED** [review]

**Review by apenalver2 — APPROVED** [review]
Thanks!!

**Comment by apenalver2** [comment]
I downloaded the Feature-66 branch and the e2e works, why Travis is failing?

**Review by dmartinezcapilla — APPROVED** [review]

**Comment by josepvilabadillo** [comment]
> I downloaded the Feature-66 branch and the e2e works, why Travis is failing?

In which resolution did you run the tests? Is it the same used in Travis? Many of the tests seem to be failing because an element is not clickable, maybe with the change in height of the AllergyDialogParameters component some elements fall out of the screen.

**Review by josepvilabadillo — APPROVED** [review]
Approved.

**Comment by alfonsserra** [comment]
> > I downloaded the Feature-66 branch and the e2e works, why Travis is failing?
> 
> In which resolution did you run the tests? Is it the same used in Travis? Many of the tests seem to be failing because an element is not clickable, maybe with the change in height of the AllergyDialogParameters component some elements fall out of the screen.

Thank you @josepvilabadillo. The problem is not related to the resolution. It is because of the animation that we have added for the modals:

.cdk-overlay-pane {
 &:not(.fullscreen) {
    animation: scaleUp .2s;
  }
}

Seems that there is an issue with Protractor as it is not able to click in a button in a modal while in the animation.

**Pull request merged**
